version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html/
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    ports:
      - 7000:80

  php:
    image: murilogp/centos-php74
    volumes:
      - ./html:/usr/share/nginx/html/
      - ./php.ini:/etc/opt/remi/php74/php.ini
      - ./supervisord.conf:/etc/supervisord.conf
    networks:
      - default
    ports:
      - "9000:9000"

  redis:
    image: redis
    networks:
      - default
